const data = {
	products: [
		{
			_id: "1",
			name: "Carrot-Orange",
			category: "Vebitables",
			image: "/images/product-1-carrot.jpg",
			price: 120,
			rating: 4.5,
			numReviews: 20,
			description: "From the farm straight to your doorstep, Guaranteed hygiene, quality and freshness.",
		},
		{
			_id: "2",
			name: "Beet",
			category: "Vebitables",
			image: "/images/product-2-beet.jpg",
			price: 200,
			rating: 4.3,
			numReviews: 10,
			description: "From the farm straight to your doorstep, Guaranteed hygiene, quality and freshness.",
		},
		{
			_id: "3",
			name: "Leeks",
			category: "Vebitables",
			image: "/images/product-3-leeks.jpg",
			price: 120,
			rating: 4.5,
			numReviews: 20,
			description: "From the farm straight to your doorstep, Guaranteed hygiene, quality and freshness.",
		},
		{
			_id: "4",
			name: "Green Beens",
			category: "Vebitables",
			image: "/images/product-4-greenbeens.jpg",
			price: 100,
			rating: 4.2,
			numReviews: 20,
			description: "From the farm straight to your doorstep, Guaranteed hygiene, quality and freshness.",
		},
		{
			_id: "5",
			name: "Carrot-Orange",
			category: "Vebitables",
			image: "/images/product-1-carrot.jpg",
			price: 240,
			rating: 4.4,
			numReviews: 20,
			description: "From the farm straight to your doorstep, Guaranteed hygiene, quality and freshness.",
		},
		{
			_id: "6",
			name: "Pumpkin - Orange",
			category: "Vebitables",
			image: "/images/product-5-pumpkin.jpg",
			price: 300,
			rating: 4.0,
			numReviews: 20,
			description: "From the farm straight to your doorstep, Guaranteed hygiene, quality and freshness.",
		},
	],
};

export default data;
